### ISSUE TITLE
Using --input (probably incorrectly) causes thread panic

### ISSUE THREAD

**Issue by AdamLeonSmith** [fgadaleta/ncode-agent#4]
adam@adamdev:~/workspace/ncode$ ./ncode-linux profile --input ~/workspace/ncode/report003.csv --publish
Publish after profile: true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Various(invalid utf-8 sequence of 1 bytes from index 4)', src/client.rs:346:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by AdamLeonSmith** [comment]
backtrace

Publish after profile: true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Various(invalid utf-8 sequence of 1 bytes from index 4

Stack backtrace:
   0: polars::frame::ser::fork::csv::add_to_utf8_builder
   1: polars::frame::ser::fork::csv::SequentialReader<R>::add_to_builders::{{closure}}
   2: polars::frame::ser::fork::csv::SequentialReader<R>::add_to_builders
   3: polars::frame::ser::fork::csv::SequentialReader<R>::as_df
   4: <polars::frame::ser::csv::CsvReader<R> as polars::frame::ser::SerReader<R>>::finish
   5: xtract::client::Frontend::run
   6: xtract::main
   7: std::rt::lang_start::{{closure}}
   8: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:348
      std::panicking::try
             at src/libstd/panicking.rs:325
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
   9: main
  10: __libc_start_main
  11: _start)', src/client.rs:346:30
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1117
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1508
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1273
  14: xtract::client::Frontend::run
  15: xtract::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  19: std::panicking::try
             at src/libstd/panicking.rs:325
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace

**Comment by fgadaleta** [comment]
I cannot replicate this error. 
It seems the csv is not valid or at least not for the client :/ 
Does this error occur only with this csv file?

**Comment by AdamLeonSmith** [comment]
I have tested with a different CSV and cannot reproduce.

The attached is the smallest CSV with which I can repro.  Believe it is because it is ISO-8859 text.

**Comment by AdamLeonSmith** [comment]
[tst2.zip](https://github.com/fgadaleta/ncode-agent/files/5792613/tst2.zip)

**Comment by AdamLeonSmith** [comment]
File is UTF-8
