### ISSUE TITLE
ncode data --all lists a data asset that I did not upload

### ISSUE THREAD

**Issue by AdamLeonSmith** [fgadaleta/ncode-agent#5]
adam@adamdev:~/workspace/ncode$ ./ncode-linux data --all
status ok 

********** DATA ASSET 0
id: f64ec7e01fa14368785ce8199a1eaa9c5649f4f5686e043d6e86cfe6460a69f9
type: local
filename: data/user_transactions_small.csv
submitted_on: 2021-01-05 17:01:24.804216
datastore: 078f8a1b-7bbf-4707-b205-cfb8fa506f8d

**Comment by fgadaleta** [comment]
Fixed. 
Please double check and feel free to close the issue after.

**Comment by AdamLeonSmith** [comment]
Now I receive a thread panic when running the same command (note, I do not have a new client binary).

```
adam@adamdev:~/workspace/ncode$ ./ncode-linux data --all
status ok 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a sequence", line: 1, column: 0)', src/client.rs:206:121
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1117
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1508
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1273
  14: xtract::client::Frontend::run
  15: xtract::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  19: std::panicking::try
             at src/libstd/panicking.rs:325
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by fgadaleta** [comment]
have you downloaded the latest?

**Comment by AdamLeonSmith** [comment]
I have not, github is still showing v01 - is it updated?

**Comment by fgadaleta** [comment]
yes
it's overwritten

Francesco Gadaleta, PhD
Director & Chief Scientist
Amethix Technologies

Mobile: +32 478 99 89 36

Schedule a call with me (https://harmonizely.com/francesco)

**Comment by AdamLeonSmith** [comment]
Downloaded.  Issue still occurs.

**Comment by fgadaleta** [comment]
ok i guess it's because there are no data assets. Will try it later with an empty list too from here

Francesco Gadaleta, PhD
Director & Chief Scientist
Amethix Technologies

Mobile: +32 478 99 89 36

Schedule a call with me (https://harmonizely.com/francesco)

**Comment by AdamLeonSmith** [comment]
Fixed in latest version
